# Generated by Django 3.1.5 on 2021-04-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DominatingFoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('transfermarkt_id', models.IntegerField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.managementagency')),
                ('foot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.dominatingfoot')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.team')),
            ],
        ),
    ]
