# Generated by Django 3.1.5 on 2021-05-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('transfermarkt_id', models.IntegerField(unique=True)),
                ('transfermarkt_hyperlink', models.URLField(unique=True)),
                ('is_excluded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('transfermarkt_hyperlink', models.CharField(max_length=200)),
                ('is_excluded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transfermarkt_hyperlink', models.URLField(unique=True)),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_team', to='football_players.team')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_team', to='football_players.team')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('transfermarkt_hyperlink', models.CharField(max_length=200)),
                ('is_data_fetched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('begin_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='transfermarkt_hyperlink',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='transfermarkt_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.player')),
            ],
        ),
    ]
