# Generated by Django 3.1.5 on 2021-05-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0002_auto_20210506_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='transfermarkt_id',
            field=models.CharField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='transfermarkt_hyperlink',
            field=models.URLField(unique=True),
        ),
    ]
