# Generated by Django 3.1.5 on 2021-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0003_auto_20210508_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='transfermarkt_hyperlink',
            field=models.URLField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
