# Generated by Django 3.1.5 on 2021-05-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0004_auto_20210508_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.league'),
            preserve_default=False,
        ),
    ]
