# Generated by Django 3.1.5 on 2021-05-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0005_season_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.season'),
            preserve_default=False,
        ),
    ]
