# Generated by Django 3.1.5 on 2021-05-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0006_queue_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='transfermarkt_hyperlink',
            field=models.URLField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='transfermarkt_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
