# Generated by Django 3.2.2 on 2021-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0007_auto_20210519_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
