# Generated by Django 3.2.2 on 2021-05-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0008_alter_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
