# Generated by Django 3.2.2 on 2021-05-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0009_alter_player_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.managementagency'),
        ),
        migrations.AlterField(
            model_name='player',
            name='foot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.dominatingfoot'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.position'),
        ),
    ]
