# Generated by Django 3.2.2 on 2021-05-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0012_match_queue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchPlayers',
            new_name='MatchPlayer',
        ),
    ]
