# Generated by Django 3.2.2 on 2021-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0013_rename_matchplayers_matchplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='all_players_from_teams_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='all_teams_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
