# Generated by Django 3.2.2 on 2021-06-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0015_teamseason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='is_data_fetched',
            new_name='are_matches_fetched',
        ),
    ]
