# Generated by Django 3.2.2 on 2021-06-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0017_alter_assist_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='football_players.match'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
