# Generated by Django 3.2.2 on 2021-06-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0018_auto_20210612_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='are_event_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
