# Generated by Django 3.1.5 on 2021-07-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_players', '0019_match_are_event_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='transfermarkt_hyperlink',
            field=models.URLField(),
        ),
    ]
